name: Publish to GH Pages

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    if: contains(github.ref, 'react-app')
    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - name: Install
        run: yarn && cd react-app && yarn

      - name: Build
        run: cd react-app && yarn run build

      - name: Deploy
        if: success()
        uses: crazy-max/ghaction-github-pages@v1.3.0
        with:
          target_branch: gh-pages
          build_dir: react-app/build
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
