name: pull-request

on: [pull_request]

jobs:
  pr-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - name: Install
        run: yarn && cd lib && yarn && cd ../react-app && yarn

      - name: Lint Check
        run: yarn lint

      - name: Format Check
        run: yarn format:check
